# Generated by Django 3.1.5 on 2021-01-09 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210109_0239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='followers',
        ),
        migrations.AddField(
            model_name='followers',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_user', to='core.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='his_followers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='his_followers', to='core.followers'),
        ),
    ]
