# Generated by Django 3.1.5 on 2021-01-09 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210109_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='his_followers',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='his_followers', to='core.followers'),
        ),
    ]
