# Generated by Django 3.1.5 on 2021-01-13 21:33

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to=core.models.post_avatar_path),
        ),
    ]
