# Generated by Django 3.1.5 on 2021-01-20 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='his_follows',
        ),
    ]
