# Generated by Django 3.1.5 on 2021-01-20 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_user_his_follows'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='his_follows',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='his_follows', to='core.follows'),
        ),
    ]
