# Generated by Django 3.1.5 on 2021-01-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='2222', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
